name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
    type: closed

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"
